version: "3"

services:
  backend:
    image: backend
    restart: always
    ports: 
      - "80:3001"
  frontend:
    image: frontend
    restart: always
    ports:
      - "81:3000"
    depends_on:
      - backend