version: "3"

services:
  backend:
    image: backend
    restart: always
    ports: 
      - "80:3001"
  frontend:
    image: frontend
    restart: always
    ports:
      - "81:3000"
    depends_on:
      - backend
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    